### ISSUE TITLE
freeDiameter generates error logs when there are no session IDs on messages that don't require session IDs

### ISSUE THREAD

**Issue by graemerobertson** [Metaswitch/freeDiameter#21] opened 2015-05-21 10:25 UTC
I've got freeDiameter running as a client and I'm seeing regular logs that look like

```
21-05-2015 10:19:40.950 UTC Debug diameterstack.cpp:781: Processing a sent diameter message
21-05-2015 10:19:40.950 UTC Debug diameterstack.cpp:783: Got existing trail ID: 0
21-05-2015 10:19:40.950 UTC Debug freeDiameter: No Session-Id AVP found in message 0x7fa1d0016d70
21-05-2015 10:19:40.950 UTC Error freeDiameter: ERROR: Invalid parameter '(( ((session) != ((void *)0)) && ( ((struct session *)(session))->eyec == 0x53551D) ) && sid)', 22
21-05-2015 10:19:40.950 UTC Debug freeDiameter: Sending 104b data on connection {----} TCP from [10.225.20.196]:35336 (11<-2007)
```

They seem to correlate with things like responding to Device-Watchdog-Requests and Capabilities-Exchange-Requests (which don't have session IDs).

There doesn't seem to be any impact on behaviour - the error log is just annoying and misleading (and wrong).

Should be easy to repro since the log seems to be generated on trying to send any DWA or CEA. Next step is probably to work out the code path in freeDiameter that leads to this log being generated (by adding more logs or by running with gdb).

**Comment by graemerobertson** [comment] 2015-05-21 10:28
This is not a completely pointless issue to fix; the logs are dropped really pretty regularly and make debugging real problems much harder.

**Comment by rkd-msw** [comment] 2015-06-04 20:46
Only place that makes sense is https://github.com/Metaswitch/freeDiameter/blob/master/libfdproto/sessions.c#L558 - but I can't see anywhere that would call fd_sess_getsid with an invalid session object.

**Comment by graemerobertson** [comment] 2015-06-05 10:18
I've also seen this log being generated in Ralf, and it seems to be generated very reliably on a DWR/DWA exchange. I am surprised I've never noticed it before though...

```
05-06-2015 10:16:49.892 UTC Debug diameterstack.cpp:761: Processing a received diameter message
05-06-2015 10:16:49.892 UTC Debug diameterstack.cpp:767: Allocated new trail ID: 51
05-06-2015 10:16:49.892 UTC Debug freeDiameter: No Session-Id AVP found in message 0x7fe784007be0
05-06-2015 10:16:49.892 UTC Error freeDiameter: ERROR: Invalid parameter '(( ((session) != ((void *)0)) && ( ((struct session *)(session))->eyec == 0x53551D) ) && sid)', 22
05-06-2015 10:16:49.892 UTC Debug freeDiameter: Iterating on rules of COMMAND: 'Device-Watchdog-Request'.
05-06-2015 10:16:49.892 UTC Debug freeDiameter: No Session-Id AVP found in message 0x7fe784007be0
05-06-2015 10:16:49.892 UTC Debug freeDiameter: Peer timeout reset to 30 seconds (+/- 2)
05-06-2015 10:16:49.892 UTC Debug freeDiameter: '10.225.20.202' in state 'STATE_OPEN' waiting for next event.
05-06-2015 10:16:49.892 UTC Debug diameterstack.cpp:781: Processing a sent diameter message
05-06-2015 10:16:49.892 UTC Debug diameterstack.cpp:783: Got existing trail ID: 0
05-06-2015 10:16:49.892 UTC Debug freeDiameter: No Session-Id AVP found in message 0x7fe78402b040
05-06-2015 10:16:49.892 UTC Error freeDiameter: ERROR: Invalid parameter '(( ((session) != ((void *)0)) && ( ((struct session *)(session))->eyec == 0x53551D) ) && sid)', 22
05-06-2015 10:16:49.892 UTC Debug freeDiameter: Sending 132b data on connection {----} TCP,#328->10.225.20.202(3868)
```

**Comment by rkd-msw** [comment] 2016-06-08 22:11
I've just looked for this on the staging Ralf and it no longer seems to repro:

```
08-06-2016 19:00:28.633 UTC Debug freeDiameter: 'STATE_OPEN'    <-- 'FDEVP_CNX_MSG_RECV'        (0x7fadec0edc10,120)    '10.0.0.83'
08-06-2016 19:00:28.633 UTC Debug freeDiameter: Iterating on rules of COMMAND: 'Device-Watchdog-Request'.
08-06-2016 19:00:28.633 UTC Debug freeDiameter: No Session-Id AVP found in message 0x7fadf00c3810
08-06-2016 19:00:28.633 UTC Debug freeDiameter: Peer timeout reset to 30 seconds (+/- 2)
08-06-2016 19:00:28.633 UTC Debug freeDiameter: '10.0.0.83' in state 'STATE_OPEN' waiting for next event.
08-06-2016 19:00:28.633 UTC Debug freeDiameter: GOING TO SEND TO '10.0.0.83': 'Device-Watchdog-Answer'0/280 f:---- src:'(nil)' len:20 {C:268/l:12,C:264/l:8,C:296/l:8,C:278/l:12}
08-06-2016 19:00:28.633 UTC Debug freeDiameter: Sending 128b data on connection {----} TCP,#392->10.0.0.83(3868)
```

I've grepped for `Error freeDiameter` in /var/log/ralf and found nothing. Should we close?

**Comment by rkd-msw** [comment] 2016-06-08 22:14
https://github.com/Metaswitch/cpp-common/commit/ae11070b835b7ddb768549ced37d157b4b8540cf#diff-f329955d52ef065591864789313a400c looks like something that might have fixed it.

**Comment by rkd-msw** [comment] 2016-06-09 17:20
Fixed by https://github.com/Metaswitch/cpp-common/issues/524, confirmed on staging Ralf.

**Closed by rkd-msw** 2016-06-09 17:20 UTC
